import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({ pages }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS with Headless Wagtail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Pages:</h1>

        <ul>
          {pages.map((page: any) => (
            <li key={page.id}>
              <span>{page.title}</span> <a href={`blog/${page.id}`}>URL</a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:8000/api/v2/pages/");
  const data = await res.json();

  return {
    props: {
      pages: data.items,
    },
  };
}

export default Home;
